---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: db
  name: cqlsh
  labels:
    app: cqlsh

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cqlsh
  template:
    metadata:
      labels:
        app: cqlsh
    spec:
      containers:
        - name: cqlsh
          image: cassandra:3.11.6
          args:
            - sleep 
            - "3600"              
          resources:
            limits:
              cpu: "500m"
              memory: 1Gi
            requests:
              cpu: "500m"
              memory: 1Gi