apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-cfgmap
  labels:
    grafana_datasource: "true"
  namespace: monitoring
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        orgId: 1
        url: http://prometheus.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true
